services:
  web:
    build:
      context: ./app
    volumes:
      - static-volume:/home/app/web/static
      - media-volume:/home/app/web/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
    - postgres-data:/var/lib/postgresql/data/
    env_file:
    - ./.env.db
  
  nginx:
    build: ./nginx
    volumes:
      - static-volume:/home/app/web/static
      - media-volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web

  volumes:
    postgres-data:
    static-volume:
    media-volume: